/*
 * Copyright (C) 2017, Amazon.com, Inc. or its affiliates. All Rights Reserved.
 *
 * This file is licensed under the terms of the GNU General Public
 * License version 2. This program is licensed "as is" without any
 * warranty of any kind, whether express or implied.
 */

#ifndef AL_ETH_REGS_H
#define AL_ETH_REGS_H

#define AL_ETH_MAC_1G			0x0
#define AL_ETH_MAC_1G_SCRATCH		(AL_ETH_MAC_1G + 0x4)
#define AL_ETH_MAC_1G_CMD_CFG		(AL_ETH_MAC_1G + 0x8)
#define AL_ETH_MAC_1G_MAC_0		(AL_ETH_MAC_1G + 0x10)
#define AL_ETH_MAC_1G_FRM_LEN		(AL_ETH_MAC_1G + 0x14)
#define AL_ETH_MAC_1G_PAUSE_QUANT	(AL_ETH_MAC_1G + 0x18)
#define AL_ETH_MAC_1G_RX_EMPTY		(AL_ETH_MAC_1G + 0x1c)
#define AL_ETH_MAC_1G_RX_FULL		(AL_ETH_MAC_1G + 0x20)
#define AL_ETH_MAC_1G_TX_EMPTY		(AL_ETH_MAC_1G + 0x24)
#define AL_ETH_MAC_1G_TX_FULL		(AL_ETH_MAC_1G + 0x28)
#define AL_ETH_MAC_1G_RX_ALMOST_EMPTY	(AL_ETH_MAC_1G + 0x2c)
#define AL_ETH_MAC_1G_RX_ALMOST_FULL	(AL_ETH_MAC_1G + 0x30)
#define AL_ETH_MAC_1G_TX_ALMOST_EMPTY	(AL_ETH_MAC_1G + 0x34)
#define AL_ETH_MAC_1G_TX_ALMOST_FULL	(AL_ETH_MAC_1G + 0x38)
#define AL_ETH_MAC_1G_PHY		(AL_ETH_MAC_1G + 0x200)

#define AL_ETH_MAC_1G_STAT		(AL_ETH_MAC_1G + 0x260)

#define AL_ETH_MAC_10G			0x400
#define AL_ETH_MAC_10G_SCRATCH		(AL_ETH_MAC_10G + 0x4)
#define AL_ETH_MAC_10G_CMD_CFG		(AL_ETH_MAC_10G + 0x8)
#define AL_ETH_MAC_10G_FRM_LEN		(AL_ETH_MAC_10G + 0x14)
#define AL_ETH_MAC_10G_MDIO_CFG_STATUS	(AL_ETH_MAC_10G + 0x30)
#define AL_ETH_MAC_10G_MDIO_CMD		(AL_ETH_MAC_10G + 0x34)
#define AL_ETH_MAC_10G_MDIO_DATA	(AL_ETH_MAC_10G + 0x38)
#define AL_ETH_MAC_10G_MDIO_REGADDR	(AL_ETH_MAC_10G + 0x3c)
#define AL_ETH_MAC_10G_CL01_PAUSE_QNTA	(AL_ETH_MAC_10G + 0x54)
#define AL_ETH_MAC_10G_CL23_PAUSE_QNTA	(AL_ETH_MAC_10G + 0x58)
#define AL_ETH_MAC_10G_CL45_PAUSE_QNTA	(AL_ETH_MAC_10G + 0x5c)
#define AL_ETH_MAC_10G_CL67_PAUSE_QNTA	(AL_ETH_MAC_10G + 0x60)
#define AL_ETH_MAC_10G_CL01_QNTA_THRES	(AL_ETH_MAC_10G + 0x64)
#define AL_ETH_MAC_10G_CL23_QNTA_THRES	(AL_ETH_MAC_10G + 0x68)
#define AL_ETH_MAC_10G_CL45_QNTA_THRES	(AL_ETH_MAC_10G + 0x6c)
#define AL_ETH_MAC_10G_CL67_QNTA_THRES	(AL_ETH_MAC_10G + 0x70)
#define AL_ETH_MAC_10G_CONTROL		(AL_ETH_MAC_10G + 0x300)
#define AL_ETH_MAC_10G_IF_MODE		(AL_ETH_MAC_10G + 0x350)

#define AL_ETH_MAC_GEN			0x900
#define AL_ETH_MAC_GEN_CFG		(AL_ETH_MAC_GEN + 0xc)
#define AL_ETH_MAC_GEN_MAC_1G_CFG	(AL_ETH_MAC_GEN + 0x10)
#define AL_ETH_MAC_GEN_RGMII_CFG	(AL_ETH_MAC_GEN + 0x18)
#define AL_ETH_MAC_GEN_RXAUI_CFG	(AL_ETH_MAC_GEN + 0x30)
#define AL_ETH_MAC_GEN_SD_CFG		(AL_ETH_MAC_GEN + 0x38)
#define AL_ETH_MAC_GEN_MDIO_CTRL_1	(AL_ETH_MAC_GEN + 0x3c)
#define AL_ETH_MAC_GEN_MDIO_1		(AL_ETH_MAC_GEN + 0x40)
#define AL_ETH_MAC_GEN_XGMII_DFIFO_32_64	(AL_ETH_MAC_GEN + 0x4c)
#define AL_ETH_MAC_GEN_XGMII_DFIFO_64_32	(AL_ETH_MAC_GEN + 0x54)
#define AL_ETH_MAC_GEN_SD_FIFO_CTRL	(AL_ETH_MAC_GEN + 0x5c)
#define AL_ETH_MAC_GEN_MUX_SEL		(AL_ETH_MAC_GEN + 0x64)
#define AL_ETH_MAC_GEN_CLK_CFG		(AL_ETH_MAC_GEN + 0x68)
#define AL_ETH_MAC_GEN_RGMII_SEL	(AL_ETH_MAC_GEN + 0x74)
#define AL_ETH_MAC_GEN_LED_CFG		(AL_ETH_MAC_GEN + 0x78)

#define AL_ETH_MAC_KR			0xa00
#define AL_ETH_MAC_KR_PCS_CFG		(AL_ETH_MAC_KR + 0x20)

#define AL_ETH_MAC_SGMII		0xb00
#define AL_ETH_MAC_SGMII_REG_ADDR	(AL_ETH_MAC_SGMII + 0x0)
#define AL_ETH_MAC_SGMII_REG_DATA	(AL_ETH_MAC_SGMII + 0x4)
#define AL_ETH_MAC_SGMII_CLK_DIV	(AL_ETH_MAC_SGMII + 0x8)

#define AL_ETH_MAC_STAT			0xc00
#define AL_ETH_MAC_STAT_EEE_IN		(AL_ETH_MAC_STAT + 0x4)
#define AL_ETH_MAC_STAT_EEE_OUT		(AL_ETH_MAC_STAT + 0x8)

#define AL_ETH_MAC_GEN_V3		0xe00
#define AL_ETH_MAC_GEN_V3_AFIFO_CTRL		(AL_ETH_MAC_GEN_V3 + 0x0)
#define AL_ETH_MAC_GEN_V3_TX_AFIFO_CFG_1	(AL_ETH_MAC_GEN_V3 + 0x4)
#define AL_ETH_MAC_GEN_V3_TX_AFIFO_CFG_2	(AL_ETH_MAC_GEN_V3 + 0x8)
#define AL_ETH_MAC_GEN_V3_TX_AFIFO_CFG_3	(AL_ETH_MAC_GEN_V3 + 0xc)
#define AL_ETH_MAC_GEN_V3_TX_AFIFO_CFG_4	(AL_ETH_MAC_GEN_V3 + 0x10)
#define AL_ETH_MAC_GEN_V3_TX_AFIFO_CFG_5	(AL_ETH_MAC_GEN_V3 + 0x14)
#define AL_ETH_MAC_GEN_V3_RX_AFIFO_CFG_1	(AL_ETH_MAC_GEN_V3 + 0x18)
#define AL_ETH_MAC_GEN_V3_RX_AFIFO_CFG_2	(AL_ETH_MAC_GEN_V3 + 0x1c)
#define AL_ETH_MAC_GEN_V3_RX_AFIFO_CFG_3	(AL_ETH_MAC_GEN_V3 + 0x20)
#define AL_ETH_MAC_GEN_V3_RX_AFIFO_CFG_4	(AL_ETH_MAC_GEN_V3 + 0x24)
#define AL_ETH_MAC_GEN_V3_RX_AFIFO_CFG_5	(AL_ETH_MAC_GEN_V3 + 0x28)
#define AL_ETH_MAC_GEN_V3_MAC_SEL		(AL_ETH_MAC_GEN_V3 + 0x2c)
#define AL_ETH_MAC_GEN_V3_MAC_10G_LL_CFG	(AL_ETH_MAC_GEN_V3 + 0x30)
#define AL_ETH_MAC_GEN_V3_MAC_10G_LL_CTRL	(AL_ETH_MAC_GEN_V3 + 0x34)
#define AL_ETH_MAC_GEN_V3_PCS_10G_LL_CFG	(AL_ETH_MAC_GEN_V3 + 0x38)
#define AL_ETH_MAC_GEN_V3_PCS_40G_LL_CFG	(AL_ETH_MAC_GEN_V3 + 0x40)
#define AL_ETH_MAC_GEN_V3_PCS_40G_LL_ADDR	(AL_ETH_MAC_GEN_V3 + 0x48)
#define AL_ETH_MAC_GEN_V3_PCS_40G_LL_DATA	(AL_ETH_MAC_GEN_V3 + 0x4c)
#define AL_ETH_MAC_GEN_V3_MAC_40G_LL_ADDR	(AL_ETH_MAC_GEN_V3 + 0x60)
#define AL_ETH_MAC_GEN_V3_MAC_40G_LL_DATA	(AL_ETH_MAC_GEN_V3 + 0x64)
#define AL_ETH_MAC_GEN_V3_PCS_40G_LL_EEE_CFG	(AL_ETH_MAC_GEN_V3 + 0x74)
#define AL_ETH_MAC_GEN_V3_SPARE			(AL_ETH_MAC_GEN_V3 + 0xb4)

#define AL_EC_GEN			0x0080

#define AL_EC_GEN_EN			(AL_EC_GEN + 0x04)
#define AL_EC_GEN_FIFO_EN		(AL_EC_GEN + 0x08)
#define AL_EC_GEN_EN_EXTENDED_OPS	(AL_EC_GEN + 0x18)

#define AL_EC_MAC			0x00c0

#define AL_EC_MAC_GEN			(AL_EC_MAC + 0x00)
#define AL_EC_MAC_MIN_PKT		(AL_EC_MAC + 0x04)
#define AL_EC_MAC_MAX_PKT		(AL_EC_MAC + 0x08)

/* MAX 2 elems */
#define AL_EC_EPE(x)			(0x0180 + (x) * 0x40)

#define AL_EC_EPE_ACT_TABLE_ADDR	0x04
#define AL_EC_EPE_ACT_TABLE_DATA_1	0x08
#define AL_EC_EPE_ACT_TABLE_DATA_2	0x0c
#define AL_EC_EPE_ACT_TABLE_DATA_3	0x10
#define AL_EC_EPE_ACT_TABLE_DATA_4	0x14
#define AL_EC_EPE_ACT_TABLE_DATA_5	0x18
#define AL_EC_EPE_ACT_TABLE_DATA_6	0x1c
#define AL_EC_EPE_RES_DEF		0x20
#define AL_EC_EPE_RES_IN		0x24

#define AL_EC_EPE_RES			0x0200

/* MAX 32 elems */
#define AL_EC_EPE_H_HDR_LEN(x)		(0x0280 + (x) * 0x04)

/* MAX 32 elems */
#define AL_EC_EPE_P(x)			(0x0300 + (x) * 0x1c)

#define AL_EC_EPE_P_COMP_DATA		0x00
#define AL_EC_EPE_P_COMP_MASK		0x04
#define AL_EC_EPE_P_COMP_CTRL		0x08

/* MAX 32 elems */
#define AL_EC_EPE_A_PROT_ACT(x)		(0x0680 + (x) * 0x04)

#define AL_EC_RFW			0x0700

#define AL_EC_RFW_THASH_CFG_1		(AL_EC_RFW + 0x00)
#define AL_EC_RFW_META			(AL_EC_RFW + 0x18)
#define AL_EC_RFW_FILTER		(AL_EC_RFW + 0x1c)
#define AL_EC_RFW_THASH_TABLE_ADDR	(AL_EC_RFW + 0x20)
#define AL_EC_RFW_THASH_TABLE_DATA	(AL_EC_RFW + 0x24)
#define AL_EC_RFW_VID_TABLE_ADDR	(AL_EC_RFW + 0x30)
#define AL_EC_RFW_VID_TABLE_DATA	(AL_EC_RFW + 0x34)
#define AL_EC_RFW_PBITS_TABLE_ADDR	(AL_EC_RFW + 0x38)
#define AL_EC_RFW_PBITS_TABLE_DATA	(AL_EC_RFW + 0x3c)
#define AL_EC_RFW_OUT_CFG		(AL_EC_RFW + 0x58)
#define AL_EC_RFW_FSM_TABLE_ADDR	(AL_EC_RFW + 0x5c)
#define AL_EC_RFW_FSM_TABLE_DATA	(AL_EC_RFW + 0x60)
#define AL_EC_RFW_CHECKSUM		(AL_EC_RFW + 0x78)
#define AL_EC_RFW_CTRL_TABLE_DEF	(AL_EC_RFW + 0xac)

/* MAX 10 elems */
#define AL_EC_RFW_HASH_KEY(x)		(0x0800 + (x) * 0x04)

/* MAX 8 elems */
#define AL_EC_RFW_PRIORITY_QUEUE(x)	(0x0828 + (x) * 0x04)

/* MAX 8 elems */
#define AL_EC_RFW_DEFAULT_OPT_1(x)	(0x0848 + (x) * 0x04)

/* MAX 32 elems */
#define AL_EC_FWD_MAC(x)		(0x0868 + (x) * 0x14)

#define AL_EC_FWD_MAC_DATA_L		0x00
#define AL_EC_FWD_MAC_DATA_H		0x04
#define AL_EC_FWD_MAC_MASK_L		0x08
#define AL_EC_FWD_MAC_MASK_H		0x0c
#define AL_EC_FWD_MAC_CTRL		0x10

#define AL_EC_TSO			0x0b00

#define AL_EC_TSO_IN_CFG		(AL_EC_TSO + 0x00)
#define AL_EC_TSO_CACHE_TABLE_ADDR	(AL_EC_TSO + 0x04)
#define AL_EC_TSO_CACHE_TABLE_DATA_1	(AL_EC_TSO + 0x08)
#define AL_EC_TSO_CACHE_TABLE_DATA_2	(AL_EC_TSO + 0x0c)
#define AL_EC_TSO_CACHE_TABLE_DATA_3	(AL_EC_TSO + 0x10)
#define AL_EC_TSO_CACHE_TABLE_DATA_4	(AL_EC_TSO + 0x14)
#define AL_EC_TSO_CFG_ADD_0		(AL_EC_TSO + 0x24)
#define AL_EC_TSO_CFG_TUNNEL		(AL_EC_TSO + 0x28)

#define AL_EC_TFW			0x0c00

/* MAX 4 elems */
#define AL_EC_TFW_UDMA(x)		(0x0c60 + (x) * 0x18)

#define AL_EC_TFW_UDMA_FWD_DEC		0x10

#define AL_EC_TMI			0x0cc0

#define AL_EC_TMI_TX_CFG		(AL_EC_TMI + 0x00)

#define AL_EC_EFC			0x0cd0

#define AL_EC_EFC_EC_PAUSE		(AL_EC_EFC + 0x00)
#define AL_EC_EFC_EC_XOFF		(AL_EC_EFC + 0x04)
#define AL_EC_EFC_XON			(AL_EC_EFC + 0x08)
#define AL_EC_EFC_RX_FIFO_HYST		(AL_EC_EFC + 0x14)
#define AL_EC_EFC_XOFF_TIMER_1G		(AL_EC_EFC + 0x1c)

/* MAX 4 elems */
#define AL_EC_FC_UDMA(x)		(0x0d00 + (x) * 0x80)

#define AL_EC_FC_UDMA_Q_PAUSE_0		0x00
#define AL_EC_FC_UDMA_Q_XOFF_0		0x44

#define AL_EC_EEE			0x1000

#define AL_EC_EEE_CFG_E			(AL_EC_EEE + 0x00)
#define AL_EC_EEE_PRE_CNT		(AL_EC_EEE + 0x04)
#define AL_EC_EEE_POST_CNT		(AL_EC_EEE + 0x08)
#define AL_EC_EEE_STOP_CNT		(AL_EC_EEE + 0x0c)

#define AL_EC_MSP			0x1700

/* MAX 32 elems */
#define AL_EC_MSP_C(x)			(0x17c0 + (x) * 0x1c)

#define AL_EC_MSP_C_P_COMP_DATA		0x00
#define AL_EC_MSP_C_P_COMP_MASK		0x04
#define AL_EC_MSP_C_P_COMP_CTRL		0x08

#define AL_EC_WOL			0x1b80

#define AL_EC_WOL_WOL_EN		(AL_EC_WOL + 0x00)
#define AL_EC_WOL_MAGIC_PSWD_L		(AL_EC_WOL + 0x04)
#define AL_EC_WOL_MAGIC_PSWD_H		(AL_EC_WOL + 0x08)
#define AL_EC_WOL_IPV6_DIP_WORD0	(AL_EC_WOL + 0x0c)
#define AL_EC_WOL_IPV6_DIP_WORD1	(AL_EC_WOL + 0x10)
#define AL_EC_WOL_IPV6_DIP_WORD2	(AL_EC_WOL + 0x14)
#define AL_EC_WOL_IPV6_DIP_WORD3	(AL_EC_WOL + 0x18)
#define AL_EC_WOL_IPV4_DIP		(AL_EC_WOL + 0x1c)
#define AL_EC_WOL_ETHERTYPE		(AL_EC_WOL + 0x20)

#endif
